#!/usr/bin/env node
var fs = require('fs');
function dockerfile(opts){
		var Dockerfile = fs.readFileSync(__dirname + '/Dockerfile').toString('ascii').replace('[GOOGLE_PROJECT]', opts.project).replace('[DEFAULT_CLUSTER_NAME]', opts.cluster).replace('[DEFAULT_CLUSTER_ZONE]', opts.zone);
    
		return Dockerfile;
}

var Termoil = require('termoil');
var kubernodes = new Termoil;
    kubernodes.name('KuberNodes Dockerfile Builder');
    kubernodes.instructions('kn-dockerfile [options]');
    kubernodes.addVersion(new Termoil.Version('1.0', true));
    kubernodes.addOption(new Termoil.Option(['-p', '--project'], 'project', new Termoil.Option.Type('value', true), 'Google Cloud Project'));
    kubernodes.addOption(new Termoil.Option(['-z', '--zone'], 'zone', new Termoil.Option.Type('value', true), 'Google Compute Cluster Zone'));
    kubernodes.addOption(new Termoil.Option(['-c', '--cluster'], 'cluster', new Termoil.Option.Type('value', true), 'Google Compute Cluster Name'));
    kubernodes.on('parsed', function(){
        process.stdout.write(dockerfile(this.get()));
    }).parse(Termoil.Skip(process.argv, 2));
