#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
if [ ! -z "$2" ]; then
  file="$2"
  docker build -t $1/${file:1:${#file}-8}:latest -f $file .;
else
  for file in .*.docker;
  do docker build -t $1/${file:1:${#file}-8}:latest -f $file .;
  done;
fi
